name: "Destroy Preview Environment"
description: "Destroy an Okteto preview environment"
inputs:
  name: 
    description: "The name of the preview environment to delete"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.name }}
branding:
  color: 'green'
  icon: 'grid'
